import './assets/ad-slider-component.css'
import './assets/automator.css'
import './assets/glyphs.css'
// import './assets/old-ui.css'
import './assets/styles.css'
// import './assets/theme-AMOLED.css'
// import './assets/theme-AMOLED Metro.css'
// import './assets/theme-Dark.css'
// import './assets/theme-Dark Metro.css'
// import './assets/theme-Inverted.css'
// import './assets/theme-Inverted Metro.css'
// import './assets/theme-Metro.css'
// import './assets/theme-S10.css'
// import './assets/theme-S11.css'
// import './assets/theme-S12.css'
// import './assets/theme-S1.css'
// import './assets/theme-S2.css'
// import './assets/theme-S3.css'
// import './assets/theme-S4.css'
// import './assets/theme-S5.css'
// import './assets/theme-S6.css'
// import './assets/theme-S7.css'
// import './assets/theme-S8.css'
// import './assets/theme-S9.css'
import './assets/time-studies.css'
import './assets/tooltips.css'
import './assets/vis-network.css'

import './assets/new-ui-styles.css'
import './assets/vue-sfc-classes.css'

import './main.scss'
import { createApp } from 'vue'
import App from './App.tsx'

createApp(App).mount('#app')
